export const metadata = {
  title: 'Terms of Service — Job Foocus',
};

export default function TermsOfServicePage() {
  return (
    <div className="max-w-[768px] mx-auto">
      <h1 className="text-[28px] font-semibold text-ink mb-2">Terms of Service</h1>
      <p className="text-[14px] text-steel mb-10">Last updated: May 26, 2026</p>

      <div className="space-y-8 text-[15px] text-ink leading-relaxed">
        <section>
          <h2 className="text-[18px] font-semibold text-ink mb-3">1. Acceptance of Terms</h2>
          <p className="text-[15px] text-steel leading-relaxed">
            By accessing or using Job Foocus, you agree to be bound by these Terms of Service and all applicable laws and regulations. If you do not agree with any part of these terms, you may not use the service. Your continued use of the platform constitutes acceptance of these terms as they may be updated from time to time.
          </p>
        </section>

        <section>
          <h2 className="text-[18px] font-semibold text-ink mb-3">2. Description of Service</h2>
          <p className="text-[15px] text-steel leading-relaxed">
            Job Foocus is a job application management and document generation platform. It allows users to track job applications, store a master resume, and generate AI-tailored resumes and cover letters for specific job postings. The service includes browser extension components, a web dashboard, and document generation powered by third-party AI APIs.
          </p>
        </section>

        <section>
          <h2 className="text-[18px] font-semibold text-ink mb-3">3. Eligibility</h2>
          <p className="text-[15px] text-steel leading-relaxed">
            You must be at least 18 years old to use Job Foocus. By using the service, you represent and warrant that you meet this age requirement and have the legal capacity to enter into this agreement. If you are using the service on behalf of an organization, you represent that you have the authority to bind that organization to these terms.
          </p>
        </section>

        <section>
          <h2 className="text-[18px] font-semibold text-ink mb-3">4. User Accounts and Responsibility</h2>
          <p className="text-[15px] text-steel leading-relaxed">
            You are responsible for maintaining the confidentiality of your account credentials and API keys required to operate the service. All activity occurring under your account is your responsibility. You agree to notify us immediately of any unauthorized use of your account. Job Foocus is not liable for any loss or damage arising from unauthorized account access or improper handling of credentials.
          </p>
        </section>

        <section>
          <h2 className="text-[18px] font-semibold text-ink mb-3">5. Acceptable Use</h2>
          <p className="text-[15px] text-steel leading-relaxed">
            You agree to use Job Foocus only for lawful job application management purposes. You must not use the service to generate fraudulent, misleading, or harmful application documents. Generating documents containing false information or misrepresenting yourself to prospective employers is strictly prohibited. You are solely responsible for the accuracy and completeness of all documents generated through the platform.
          </p>
        </section>

        <section>
          <h2 className="text-[18px] font-semibold text-ink mb-3">6. AI-Generated Content</h2>
          <p className="text-[15px] text-steel leading-relaxed">
            Documents generated by Job Foocus are AI-assisted drafts — not legal, professional, or factual guarantees. The output is based on your master resume data and the job description you provide, and its accuracy, completeness, or fitness for any particular application is your sole responsibility. Review all generated documents before submitting them to any employer. Job Foocus disclaims any liability for outcomes resulting from the use of AI-generated content.
          </p>
        </section>

        <section>
          <h2 className="text-[18px] font-semibold text-ink mb-3">7. Third-Party Services and APIs</h2>
          <p className="text-[15px] text-steel leading-relaxed">
            Job Foocus relies on third-party services, including the MiniMax API, for AI document generation. These services are subject to their own terms and privacy policies. We do not guarantee the continuous availability, accuracy, or reliability of any third-party service. Job Foocus reserves the right to modify, replace, or discontinue reliance on any third-party API without notice.
          </p>
        </section>

        <section>
          <h2 className="text-[18px] font-semibold text-ink mb-3">8. Intellectual Property</h2>
          <p className="text-[15px] text-steel leading-relaxed">
            All original content, design, branding, code, and materials produced by Job Foocus are the intellectual property of Job Foocus. Your master resume data, job descriptions, and any documents you input remain your property. You retain full ownership of all content you provide. Job Foocus claims no ownership over user-submitted data — you grant us a limited license to process it solely for the purpose of operating the service.
          </p>
        </section>

        <section>
          <h2 className="text-[18px] font-semibold text-ink mb-3">9. Disclaimers and Limitation of Liability</h2>
          <p className="text-[15px] text-steel leading-relaxed">
            Job Foocus is provided "as is" and "as available" without warranties of any kind, express or implied. We do not guarantee that the service will be uninterrupted, error-free, or free of viruses. To the maximum extent permitted by law, Job Foocus and its creators disclaims all liability for any direct, indirect, incidental, special, or consequential damages arising from your use of the service, including but not limited to damages arising from reliance on AI-generated content, loss of data, or business interruption.
          </p>
        </section>

        <section>
          <h2 className="text-[18px] font-semibold text-ink mb-3">10. Indemnification</h2>
          <p className="text-[15px] text-steel leading-relaxed">
            You agree to indemnify, defend, and hold harmless Job Foocus, its creators and contributors from and against any claims, liabilities, damages, losses, or expenses (including reasonable legal fees) arising from your use of the platform, your violation of these terms, or your submission of inaccurate or fraudulent application documents.
          </p>
        </section>

        <section>
          <h2 className="text-[18px] font-semibold text-ink mb-3">11. Modifications to Terms</h2>
          <p className="text-[15px] text-steel leading-relaxed">
            We reserve the right to revise these Terms of Service at any time without prior notice. Material changes will be communicated by updating the "Last updated" date at the top of this page. Continued use of Job Foocus after any such changes constitutes your acceptance of the revised terms. It is your responsibility to review these terms periodically.
          </p>
        </section>

        <section>
          <h2 className="text-[18px] font-semibold text-ink mb-3">12. Governing Law</h2>
          <p className="text-[15px] text-steel leading-relaxed">
            These Terms of Service are governed by and construed in accordance with the laws of the applicable jurisdiction, without regard to its conflict of law principles. Any disputes arising from or related to these terms or your use of the service shall be resolved exclusively in the competent courts of that jurisdiction.
          </p>
        </section>

        <section>
          <h2 className="text-[18px] font-semibold text-ink mb-3">13. Contact</h2>
          <p className="text-[15px] text-steel leading-relaxed">
            If you have questions about these Terms of Service, please contact us at{' '}
            <a href="mailto:legal@jobfoocus.com" className="text-primary hover:underline">
              legal@jobfoocus.com
            </a>.
          </p>
        </section>
      </div>
    </div>
  );
}
